GET http://localhost:8080/calc

###

GET http://localhost:8080/logout

###

POST http://localhost:8080/reg
Content-Type: application/x-www-form-urlencoded

login=test&name=Test&password=12345678

###

POST http://localhost:8080/home?type=auth
Content-Type: application/x-www-form-urlencoded

login=test&password=12345678

###

